version: "3.3"
services:
  api:
    build:
      context: ../api
      dockerfile: ../docker/api.Dockerfile
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../api:/usr/src/api
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file: ../.env
    environment:
      WAIT_HOSTS: redis:6379, db:3306
      WAIT_HOSTS_TIMEOUT: 120
    depends_on: 
      - db
  
  client:
    build:
      context: ../client
      dockerfile: ../docker/client.Dockerfile
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../client:/usr/src/client
    expose:
      - 8080
    ports:
      - 8080:8080
    env_file: ../.env
  
  db:
    build:
      context: ../db
      dockerfile: ../docker/db.Dockerfile
    ports:
      - 3306
    expose:
      - 3306
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: mediatracker
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    driver: bridge
