version: "3.3"
services:
  api:
    build:
      context: ../api
      dockerfile: ../docker/api.Dockerfile
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../api:/usr/src/api
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file: ../.env
    environment:
      WAIT_HOSTS: db:${SQL_PORT}, redis:6379
      WAIT_HOSTS_TIMEOUT: 120
  
  client:
    build:
      context: ../client
      dockerfile: ../docker/client.Dockerfile
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../client:/usr/src/client
    expose:
      - 8080
    ports:
      - 8080:8080
    env_file: ../.env
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_UESR: root
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - ../.env

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    driver: bridge
